// Copyright Istio Authors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: extensions/v1alpha1/lua.proto

// $schema: istio.extensions.v1alpha1.LuaPlugin
// $title: Lua Plugin
// $description: Extend the functionality provided by the Istio proxy through Lua scripts.
// $location: https://istio.io/docs/reference/config/proxy_extensions/lua-plugin.html
// $aliases: [/docs/reference/config/extensions/v1alpha1/lua-plugin]

// LuaPlugins provides a mechanism to extend the functionality provided by
// the Istio proxy through Lua scripts.
//
// The order of execution (as part of Envoy's filter chain) is determined by
// phase and priority settings, allowing the configuration of complex
// interactions between user-supplied LuaPlugins and Istio's internal
// filters.
//
// Examples:
//
// Basic Lua filter for request header manipulation:
//
// ```yaml
// apiVersion: extensions.istio.io/v1alpha1
// kind: LuaPlugin
// metadata:
//   name: header-modifier
//   namespace: istio-system
// spec:
//   selector:
//     matchLabels:
//       istio: ingressgateway
//   phase: AUTHN
//   inlineCode: |
//     function envoy_on_request(request_handle)
//       request_handle:headers():add("x-custom-header", "added-by-lua")
//     end
// ```
//
// More complex example with priority and traffic matching:
//
// ```yaml
// apiVersion: extensions.istio.io/v1alpha1
// kind: LuaPlugin
// metadata:
//   name: conditional-header-modifier
//   namespace: istio-ingress
// spec:
//   selector:
//     matchLabels:
//       istio: ingressgateway
//   match:
//   - mode: CLIENT
//     ports:
//     - number: 8080
//     - number: 8081
//   phase: AUTHN
//   priority: 1000
//   inlineCode: |
//     function envoy_on_request(request_handle)
//       local domain = "foo.com"
//       local headers = request_handle:headers()
//       local host = headers:get(":authority")
//       local existing_auth_header = headers:get("Authorization")
//       if (domain ~= nil and host ~= nil and existing_auth_header == nil and domain == host) then
//         bearer_token = headers:get("cookie"):match("foo")
//         if (bearer_token ~= nil) then
//           headers:add("Authorization", "Bearer " .. bearer_token)
//         end
//       end
//     end
// ```
//

package v1alpha1

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1beta1 "istio.io/api/type/v1beta1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LuaPlugin provides a mechanism to extend the functionality provided by
// the Istio proxy through Lua scripts.
//
// <!-- crd generation tags
// +cue-gen:LuaPlugin:groupName:extensions.istio.io
// +cue-gen:LuaPlugin:versions:v1alpha1
// +cue-gen:LuaPlugin:storageVersion
// +cue-gen:LuaPlugin:annotations:helm.sh/resource-policy=keep
// +cue-gen:LuaPlugin:labels:app=istio-pilot,chart=istio,heritage=Tiller,release=istio
// +cue-gen:LuaPlugin:subresource:status
// +cue-gen:LuaPlugin:spec:required
// +cue-gen:LuaPlugin:scope:Namespaced
// +cue-gen:LuaPlugin:releaseChannel:extended
// +cue-gen:LuaPlugin:resource:categories=istio-io,extensions-istio-io
// +cue-gen:LuaPlugin:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=extensions.istio.io/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
// +kubebuilder:validation:XValidation:message="only one of targetRefs or selector can be set",rule="oneof(self.selector, self.targetRef, self.targetRefs)"
type LuaPlugin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Criteria used to select the specific set of pods/VMs on which
	// this plugin configuration should be applied. If omitted, this
	// configuration will be applied to all workload instances in the same
	// namespace. If the `LuaPlugin` is present in the config root
	// namespace, it will be applied to all applicable workloads in any
	// namespace.
	//
	// At most, only one of `selector` or `targetRefs` can be set for a given policy.
	Selector *v1beta1.WorkloadSelector `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// $hide_from_docs
	TargetRef *v1beta1.PolicyTargetReference `protobuf:"bytes,2,opt,name=targetRef,proto3" json:"targetRef,omitempty"`
	// Optional. The targetRefs specifies a list of resources the policy should be
	// applied to. The targeted resources specified will determine which workloads
	// the policy applies to.
	//
	// Currently, the following resource attachment types are supported:
	// * `kind: Gateway` with `group: gateway.networking.k8s.io` in the same namespace.
	// * `kind: GatewayClass` with `group: gateway.networking.k8s.io` in the root namespace.
	// * `kind: Service` with `group: ""` or `group: "core"` in the same namespace. This type is only supported for waypoints.
	// * `kind: ServiceEntry` with `group: networking.istio.io` in the same namespace.
	//
	// If not set, the policy is applied as defined by the selector.
	// At most one of the selector and targetRefs can be set.
	//
	// NOTE: If you are using the `targetRefs` field in a multi-revision environment with Istio versions prior to 1.22,
	// it is highly recommended that you pin the policy to a revision running 1.22+ via the `istio.io/rev` label.
	// This is to prevent proxies connected to older control planes (that don't know about the `targetRefs` field)
	// from misinterpreting the policy as namespace-wide during the upgrade process.
	//
	// NOTE: Waypoint proxies are required to use this field for policies to apply; `selector` policies will be ignored.
	// +kubebuilder:validation:MaxItems=16
	TargetRefs []*v1beta1.PolicyTargetReference `protobuf:"bytes,3,rep,name=targetRefs,proto3" json:"targetRefs,omitempty"`
	// Determines where in the filter chain this `LuaPlugin` is to be injected.
	Phase PluginPhase `protobuf:"varint,4,opt,name=phase,proto3,enum=istio.extensions.v1alpha1.PluginPhase" json:"phase,omitempty"`
	// Determines ordering of `LuaPlugins` in the same `phase`.
	// When multiple `LuaPlugins` are applied to the same workload in the
	// same `phase`, they will be applied by priority, in descending order.
	// If `priority` is not set, or two `LuaPlugins` exist with the same
	// value, the ordering will be deterministically derived from name and
	// namespace of the `LuaPlugins`. Defaults to `0`.
	Priority *wrappers.Int32Value `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// Specifies the criteria to determine which traffic is passed to LuaPlugin.
	// If a traffic satisfies any of TrafficSelectors,
	// the traffic passes the LuaPlugin.
	Match []*TrafficSelector `protobuf:"bytes,6,rep,name=match,proto3" json:"match,omitempty"`
	// The inline Lua script that will be executed by the Envoy Lua filter.
	// This script should implement the required Envoy Lua filter callbacks
	// such as envoy_on_request() and envoy_on_response().
	//
	// The script has access to the standard Envoy Lua APIs for header manipulation,
	// request/response body access, and other proxy operations.
	// +kubebuilder:validation:MinLength=1
	InlineCode    string `protobuf:"bytes,7,opt,name=inlineCode,proto3" json:"inlineCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuaPlugin) Reset() {
	*x = LuaPlugin{}
	mi := &file_extensions_v1alpha1_lua_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuaPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuaPlugin) ProtoMessage() {}

func (x *LuaPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_v1alpha1_lua_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuaPlugin.ProtoReflect.Descriptor instead.
func (*LuaPlugin) Descriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_lua_proto_rawDescGZIP(), []int{0}
}

func (x *LuaPlugin) GetSelector() *v1beta1.WorkloadSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *LuaPlugin) GetTargetRef() *v1beta1.PolicyTargetReference {
	if x != nil {
		return x.TargetRef
	}
	return nil
}

func (x *LuaPlugin) GetTargetRefs() []*v1beta1.PolicyTargetReference {
	if x != nil {
		return x.TargetRefs
	}
	return nil
}

func (x *LuaPlugin) GetPhase() PluginPhase {
	if x != nil {
		return x.Phase
	}
	return PluginPhase_UNSPECIFIED_PHASE
}

func (x *LuaPlugin) GetPriority() *wrappers.Int32Value {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *LuaPlugin) GetMatch() []*TrafficSelector {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *LuaPlugin) GetInlineCode() string {
	if x != nil {
		return x.InlineCode
	}
	return ""
}

var File_extensions_v1alpha1_lua_proto protoreflect.FileDescriptor

const file_extensions_v1alpha1_lua_proto_rawDesc = "" +
	"\n" +
	"\x1dextensions/v1alpha1/lua.proto\x12\x19istio.extensions.v1alpha1\x1a\x1eextensions/v1alpha1/wasm.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1btype/v1beta1/selector.proto\"\xc0\x03\n" +
	"\tLuaPlugin\x12@\n" +
	"\bselector\x18\x01 \x01(\v2$.istio.type.v1beta1.WorkloadSelectorR\bselector\x12G\n" +
	"\ttargetRef\x18\x02 \x01(\v2).istio.type.v1beta1.PolicyTargetReferenceR\ttargetRef\x12I\n" +
	"\n" +
	"targetRefs\x18\x03 \x03(\v2).istio.type.v1beta1.PolicyTargetReferenceR\n" +
	"targetRefs\x12<\n" +
	"\x05phase\x18\x04 \x01(\x0e2&.istio.extensions.v1alpha1.PluginPhaseR\x05phase\x127\n" +
	"\bpriority\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\bpriority\x12@\n" +
	"\x05match\x18\x06 \x03(\v2*.istio.extensions.v1alpha1.TrafficSelectorR\x05match\x12$\n" +
	"\n" +
	"inlineCode\x18\a \x01(\tB\x04\xe2A\x01\x02R\n" +
	"inlineCodeB\"Z istio.io/api/extensions/v1alpha1b\x06proto3"

var (
	file_extensions_v1alpha1_lua_proto_rawDescOnce sync.Once
	file_extensions_v1alpha1_lua_proto_rawDescData []byte
)

func file_extensions_v1alpha1_lua_proto_rawDescGZIP() []byte {
	file_extensions_v1alpha1_lua_proto_rawDescOnce.Do(func() {
		file_extensions_v1alpha1_lua_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_v1alpha1_lua_proto_rawDesc), len(file_extensions_v1alpha1_lua_proto_rawDesc)))
	})
	return file_extensions_v1alpha1_lua_proto_rawDescData
}

var file_extensions_v1alpha1_lua_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extensions_v1alpha1_lua_proto_goTypes = []any{
	(*LuaPlugin)(nil),                     // 0: istio.extensions.v1alpha1.LuaPlugin
	(*v1beta1.WorkloadSelector)(nil),      // 1: istio.type.v1beta1.WorkloadSelector
	(*v1beta1.PolicyTargetReference)(nil), // 2: istio.type.v1beta1.PolicyTargetReference
	(PluginPhase)(0),                      // 3: istio.extensions.v1alpha1.PluginPhase
	(*wrappers.Int32Value)(nil),           // 4: google.protobuf.Int32Value
	(*TrafficSelector)(nil),               // 5: istio.extensions.v1alpha1.TrafficSelector
}
var file_extensions_v1alpha1_lua_proto_depIdxs = []int32{
	1, // 0: istio.extensions.v1alpha1.LuaPlugin.selector:type_name -> istio.type.v1beta1.WorkloadSelector
	2, // 1: istio.extensions.v1alpha1.LuaPlugin.targetRef:type_name -> istio.type.v1beta1.PolicyTargetReference
	2, // 2: istio.extensions.v1alpha1.LuaPlugin.targetRefs:type_name -> istio.type.v1beta1.PolicyTargetReference
	3, // 3: istio.extensions.v1alpha1.LuaPlugin.phase:type_name -> istio.extensions.v1alpha1.PluginPhase
	4, // 4: istio.extensions.v1alpha1.LuaPlugin.priority:type_name -> google.protobuf.Int32Value
	5, // 5: istio.extensions.v1alpha1.LuaPlugin.match:type_name -> istio.extensions.v1alpha1.TrafficSelector
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_extensions_v1alpha1_lua_proto_init() }
func file_extensions_v1alpha1_lua_proto_init() {
	if File_extensions_v1alpha1_lua_proto != nil {
		return
	}
	file_extensions_v1alpha1_wasm_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_v1alpha1_lua_proto_rawDesc), len(file_extensions_v1alpha1_lua_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_v1alpha1_lua_proto_goTypes,
		DependencyIndexes: file_extensions_v1alpha1_lua_proto_depIdxs,
		MessageInfos:      file_extensions_v1alpha1_lua_proto_msgTypes,
	}.Build()
	File_extensions_v1alpha1_lua_proto = out.File
	file_extensions_v1alpha1_lua_proto_goTypes = nil
	file_extensions_v1alpha1_lua_proto_depIdxs = nil
}
