// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using LuaPlugin within kubernetes types, where deepcopy-gen is used.
func (in *LuaPlugin) DeepCopyInto(out *LuaPlugin) {
	p := proto.Clone(in).(*LuaPlugin)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LuaPlugin. Required by controller-gen.
func (in *LuaPlugin) DeepCopy() *LuaPlugin {
	if in == nil {
		return nil
	}
	out := new(LuaPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LuaPlugin. Required by controller-gen.
func (in *LuaPlugin) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
