// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for LuaPlugin
func (this *LuaPlugin) MarshalJSON() ([]byte, error) {
	str, err := LuaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LuaPlugin
func (this *LuaPlugin) UnmarshalJSON(b []byte) error {
	return LuaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	LuaMarshaler   = &jsonpb.Marshaler{}
	LuaUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
